// @version=6
indicator(title="Unicorn All Indicators", shorttitle="UAI", overlay=true, timeframe="", timeframe_gaps=true)

// 在控制面板添加指标项开关
at_show_ema = input(false, title="是否显示 - EMA移动平均线")
at_show_boll = input(false, title="是否显示 - Boll线")

// EMA
// 在控制面板添加指标参数修改项
ema_len = input.int(defval = 7, minval = 1, title = "EMA-短")
ema_len1 = input.int(defval = 15, minval = 1, title = "EMA-中")
ema_len2 = input.int(defval = 60, minval = 1, title = "EMA-长")

plot(ta.ema(close, ema_len), title="EMA-短", color=at_show_ema ? color.new(color.blue, 0) : color.new(color.blue, 100), offset=0)
plot(ta.ema(close, ema_len1), title="EMA-中", color=at_show_ema ? color.new(color.green, 0) : color.new(color.green, 100), offset=0)
plot(ta.ema(close, ema_len2), title="EMA-长", color=at_show_ema ? color.new(color.red, 0) : color.new(color.red, 100), offset=0)

// Bollinger Bands
length = input.int(20, minval=1, title="BOll-长度")
maType = input.string("SMA", "Basis MA Type", options = ["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
src = input(close, title="Source")
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev")

ma(source, length, _type) =>
    switch _type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)

basis = ma(src, length, maType)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input.int(0, "Offset", minval = -500, maxval = 500, display = display.data_window)
plot(basis, "Basis", color = at_show_boll ? color.new(color.purple, 0) : color.new(color.purple, 100), offset = offset)
p1 = plot(upper, "Upper", color = at_show_boll ? color.new(color.yellow, 0) : color.new(color.yellow, 100), offset = offset)
p2 = plot(lower, "Lower", color = at_show_boll ? color.new(color.gray, 0) : color.new(color.gray, 100), offset = offset)
fill(p1, p2, title = "Background", color = at_show_boll ? color.new(color.rgb(33, 150, 243), 90) : color.new(color.rgb(33, 150, 243), 100))
